name: Linting a PR
run-name: Lint the PR of ${{ github.actor }}

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - reopened

jobs:
  lint:
    name: Linting
    runs-on: ubuntu-latest # Replace with self-hosted runner if needed
    timeout-minutes: 10

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
          run_install: false

      # Has to be done after installing pnpm, otherwise the cache will not work.
      - name: Set node version to 22
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "pnpm"
          cache-dependency-path: "pnpm-lock.yaml"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run lint
        run: pnpm run lint

      - name: Run type checking
        run: pnpm run typecheck
